// Read-only course guidance. Never write actions, people, mastery or submissions.
const $ = id => document.getElementById(id);
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = value => new Date(value+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
const list = rows => rows.map(r=>`<li>${esc(r)}</li>`).join('');
const company = window.DIP?.company;
let course, view='deliveries', selected, brief='';
$('rulesOpen').disabled=true;
function toast(text){$('labToast').textContent=text;$('labToast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('labToast').hidden=true,6000);}
function sourceText(id){const s=course.sources[id];return `${s.title} — ${s.locator}`;}
function sources(ids){return `<details class="source-details"><summary>Where the requirements and proposals come from</summary><p>Dates are the published syllabus dates, not submission status. USAC requirements and published course requirements are labelled separately. Build ideas and preparation steps are instructor proposals; your team chooses and ratifies its decisions.</p><ul>${ids.map(id=>{const s=course.sources[id];return `<li><strong>${esc(s.title)}</strong> — ${esc(s.locator)} ${s.href?`<a href="${esc(s.href)}">Read the included student document ↗</a>`:s.path?`<br>Included workspace file: <code>${esc(s.path)}</code>`:esc(s.availability)}</li>`;}).join('')}</ul></details>`;}
function actions(item){return `<div class="brief-actions"><button type="button" class="primary" id="copyBrief">Copy preparation brief ↗</button><button type="button" id="downloadBrief">Download brief ↓</button></div><details class="brief-preview" id="briefPreview"><summary>Read the brief before using it</summary><pre id="briefText">${esc(makeBrief(item))}</pre></details>`;}
function makeBrief(item){
 const isTopic='n' in item;
 const name=isTopic?`Topic ${String(item.n).padStart(2,'0')} — ${item.title}`:item.name;
 const realCompany=company?.sample===false && company.name && company.name!=='—';
 const lines=[`# Learning Lab · ${name}`,'',
  'Help me prepare and build this piece of our AI for Business company. Keep my own understanding and analysis visible. Give me drafts, tests and evidence questions, not a submission presented as my finished work.',
  'Work in the city workspace root: corners-city/ inside the team repository, or the standalone kit folder containing start.py and board/. Read CLAUDE.md and AGENTS.md first.',
  'Read 00 - Manual/MANUAL.md, board/data/company.js, 03 - Deliverables/CHECKLISTS.md and board/COURSE-SYSTEM-PROMPT.md. Inspect existing relevant code, records and playbooks before proposing changes.',
  realCompany?`Current source-file company context: ${company.name} — ${company.purpose}`:'The supplied board may still contain sample data. Ask for the company purpose/context if it is not established; do not invent it.',
  '',`Published syllabus date: ${date(item.date)} · session ${isTopic?item.n:item.session}. This is not a completion claim.`];
 if(isTopic){lines.push('',`USAC outline topic: ${item.title}`,`Knowledge to demonstrate: ${item.knowledge}`,`Competence references: ${item.competences.join(', ')}. Read their definitions in board/data/company.js and the System Prompt.`, '',`Instructor proposal to consider: ${item.build}`,`Workspace location: ${item.path}`,`Existing board entry: board/index.html#${item.entry}`, '', 'Proposed preparation/build steps:');}
 else{lines.push('',`Assessment category: ${item.bucket}`,'Required contents (authority shown):',...item.required.map(r=>`- [${r.authority}] ${r.text}\n  Evidence: ${r.evidence}\n  Review: ${r.review}`),'','Proposed preparation steps:');}
 lines.push(...item.steps.map((s,i)=>`${i+1}. ${s}`),'','Decisions still mine/the team\'s:',...item.decisions.map(s=>`- ${s}`));
 if(isTopic)lines.push('','Evidence to prepare:',...item.evidence.map(s=>`- ${s}`),'Record real commitments only in the existing board/data/actions.js PDCA system. Keep decisions in 01 - Registry/DECISIONS.md, reusable methods in 04 - Playbooks/ and competence claims in the existing Mastery screen with real proof.');
 else lines.push('','Use 03 - Deliverables/ for the package, 04 - Playbooks/ for repeatable methods and 01 - Registry/ for actual decisions. Use the Manual\'s published definition of done; do not invent an assessment rule.');
 if(item.note)lines.push('',`Source/context note: ${item.note}`);
 if(isTopic&&item.n===21)lines.push('','Source note: the published term outline still says Event budget. The current course plan uses ROI of the company\'s work. Do not treat this as a new event-budget assignment; ask the instructor to clarify the published label.');
 if(isTopic&&item.n>=16&&item.n<=18)lines.push('','Source note: Make is named in the official Mini Project 2 description; course materials also allow n8n. Confirm acceptance before choosing n8n for that submission.');
 if(!isTopic&&item.id==='final-project')lines.push('','Official solution routes:',...course.solutionRoutes.map(r=>`- ${r.name}: ${r.requires}`),'The 3 December project date and 15 December term final presentation are different; do not treat the latter as an extension.');
 lines.push('','Check what actually exists. Report evidence, missing pieces and what needs human judgement. Do not mark work delivered, approved or mastered because a template or building exists. Do not calculate grades, assign people/roles, change dates/weights or create another tracker.',
  'Use invented or own data; no personal contacts, grades, secrets or third-party personal data in the repository. Name/cite tools, use quotation marks for generated passages and leave a first-name contribution/footer to be reviewed and signed by the human author.',
  'Prepare locally. Do not send notifications to others, publish, deploy or upload without explicit human authorisation. Use available course tools; do not install services or require spending based on this brief.',
  'After any board data edit, run python3 board/check.py (Windows: py -3 board/check.py). Verify the actual feature/evidence and give me one concrete next step.',
  '', 'Source references:',...item.sourceRefs.map(id=>`- ${sourceText(id)}`),'Source mapping and instructor proposals: board/learning-lab-data.json.');
 return lines.join('\n')+'\n';
}
function route(path,entry){return `<p class="workspace-path">Build in your local workspace: <code>${esc(path)}</code></p><p class="detail-caption">Folder paths refer to the included source files. The local server serves board/; use your editor for these folders.</p><div class="workspace-route"><a href="index.html#${esc(entry)}">Open existing ${esc(company?.teams?.find(t=>t.id===entry)?.name || entry)} screen ↗</a><a href="index.html#pdca">Existing PDCA ↗</a><a href="index.html#mastery">Existing Mastery ↗</a></div>`;}
function renderDelivery(d){
 const related=d.topics.map(n=>course.topics.find(t=>t.n===n));
 const calendar=company?.calendar?.find(s=>s.n===d.session);
 const mismatch=calendar && calendar.date!==d.date;
 $('detail').innerHTML=`<div class="detail-meta"><span class="badge">${d.kind==='case'?'Course case study':'Official delivery'}</span><span class="date">${esc(date(d.date))} · session ${d.session}</span></div><h2>${esc(d.name)}</h2><p class="detail-lead">${esc(d.subtitle)}</p><p class="detail-caption">${esc(d.bucket)} · syllabus date</p>${mismatch?'<p class="detail-note">The board calendar differs from the published syllabus date shown here. Ask the instructor to reconcile it.</p>':''}<p class="detail-note">${esc(d.note)}</p><div class="section-head"><h3>Prepare it step by step.</h3><span class="eyebrow">INSTRUCTOR PROPOSAL</span></div><ol class="steps">${list(d.steps)}</ol><h3>Review the evidence.</h3><p class="detail-caption">A preparation checklist, not an approval. Expand each item and compare it with your real work.</p><div class="criteria">${d.required.map((r,i)=>`<details class="criterion" ${i===0?'open':''}><summary><span><span class="badge">${esc(r.authority)}</span>${esc(r.text)}</span></summary><dl><dt>Evidence</dt><dd>${esc(r.evidence)}</dd><dt>Review</dt><dd>${esc(r.review)}</dd></dl></details>`).join('')}</div>${d.id==='final-project'?`<h3>Choose your official solution route.</h3><ul class="evidence-list">${course.solutionRoutes.map(r=>`<li><strong>${esc(r.name)}:</strong> ${esc(r.requires)}</li>`).join('')}</ul>`:''}<h3>Decisions that stay yours.</h3><ul class="choices">${list(d.decisions)}</ul>${route('03 - Deliverables/','operations')}<p class="detail-caption">Reuse the Manual’s definition of done, Registry decisions, Playbooks and the existing board. Review before the date is unlimited; the delivery date is real.</p>${actions(d)}<h3>Build the pieces behind this delivery.</h3><div class="workspace-route">${related.map(t=>`<a href="#topics/${t.n}">${String(t.n).padStart(2,'0')} · ${esc(t.build)} ↗</a>`).join('')}</div>${sources(d.sourceRefs)}`;
}
function renderTopic(t){
 const b=course.blocks.find(b=>b.id===t.block);
 $('detail').innerHTML=`<div class="detail-meta"><span class="badge">USAC outline · ${String(t.n).padStart(2,'0')}/25</span><span class="date">${esc(date(t.date))} · ${esc(b.title)}</span></div><h2>${esc(t.title)}</h2><p class="detail-lead">${esc(t.knowledge)}</p><p class="detail-caption">${t.competences.map(id=>`<span title="${esc(company?.competences?.find(c=>c.id===id)?.text || id)}">${esc(id)}</span>`).join(' · ')} · existing competence references, not new mastery claims</p><div class="build-chain"><span class="chain-arrow" aria-hidden="true">↳</span><div><p class="eyebrow">INSTRUCTOR BUILD PROPOSAL</p><strong>${esc(t.build)}</strong><p>A minimum useful piece to consider. Adapt it to your company; it is not an assigned project or a new assessment condition.</p></div></div>${t.n===21?`<p class="detail-note">Source note: the published outline says “Event budget”; the current plan uses ROI of your company’s work. <button type="button" class="route-link" data-source-notes>Read the discrepancy</button></p>`:''}${t.n>=16&&t.n<=18?'<p class="detail-note">For Mini Project 2, Make fits both source texts; confirm n8n acceptance with the instructor. See course rules & sources.</p>':''}<div class="section-head"><h3>Start with one useful action.</h3><span class="eyebrow">INSTRUCTOR PROPOSAL</span></div><ol class="steps">${list(t.steps)}</ol><h3>Evidence to prepare.</h3><ul class="evidence-list">${list(t.evidence)}</ul>${route(t.path,t.entry)}<h3>Decisions that stay yours.</h3><ul class="choices">${list(t.decisions)}</ul>${actions(t)}<div class="workspace-route">${t.deliveries.map(id=>{const d=course.deliveries.find(d=>d.id===id);return `<a href="#deliveries/${esc(id)}">Prepare ${esc(d.name)} ↗</a>`;}).join('')}</div>${sources(t.sourceRefs)}<div class="next-topic"><button type="button" id="previousTopic" ${t.n===1?'disabled':''}>← Previous topic</button><button type="button" id="nextTopic" ${t.n===25?'disabled':''}>Next topic →</button></div>`;
 $('previousTopic').onclick=()=>chooseTopic(t.n-1);$('nextTopic').onclick=()=>chooseTopic(t.n+1);
 $('detail').querySelector('[data-source-notes]')?.addEventListener('click',()=>openRules(true));
}
function chooseTopic(n){$('topicSearch').value='';$('blockFilter').value='';location.hash=`topics/${n}`;}
function bindBrief(item){
 brief=makeBrief(item);
 $('copyBrief').onclick=async()=>{
  try{if(!navigator.clipboard?.writeText)throw Error('Clipboard unavailable');await navigator.clipboard.writeText(brief);toast('Preparation brief copied. Review it and supply your team’s decisions.');}
  catch(e){$('briefPreview').open=true;const selection=getSelection();const range=document.createRange();range.selectNodeContents($('briefText'));selection.removeAllRanges();selection.addRange(range);$('briefPreview').scrollIntoView({block:'nearest'});toast('Automatic copy is unavailable. The brief is selected; use your browser’s Copy command.');}
 };
 $('downloadBrief').onclick=()=>{const blob=new Blob([brief],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`learning-lab-${'n' in item?'topic-'+String(item.n).padStart(2,'0'):item.id}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Brief downloaded. It records preparation guidance, not submitted work.');};
}
function filteredTopics(){const q=$('topicSearch').value.trim().toLowerCase(),block=$('blockFilter').value;return course.topics.filter(t=>(!block||t.block===Number(block))&&(!q||`${t.n} ${t.title} ${t.build} ${t.knowledge} ${t.competences.join(' ')}`.toLowerCase().includes(q)));}
function render(){
 const topics=view==='topics';const rows=topics?filteredTopics():[...course.deliveries,...course.caseStudies];
 $('topicFilters').hidden=!topics;
 for(const [id,on] of [['topicsTab',topics],['deliveriesTab',!topics]]){$(id).setAttribute('aria-selected',String(on));$(id).tabIndex=on?0:-1;}
 $('workbench').setAttribute('aria-labelledby',topics?'topicsTab':'deliveriesTab');
 $('menuHint').textContent=topics?`${rows.length} of 25 topics · syllabus order`:'Four official deliveries · syllabus dates';
 if(!rows.some(r=>(topics?r.n:r.id)===selected))selected=topics?rows[0]?.n:rows[0]?.id;
 const menuButton=(r,i)=>{const id=topics?r.n:r.id;return `<button type="button" class="item-button" data-item="${esc(id)}" aria-current="${id===selected}"><span class="item-num">${String(topics?r.n:r.kind==='case'?i-3:i+1).padStart(2,'0')}</span><span>${esc(topics?r.build:r.name)}<small>${esc(topics?r.title:date(r.date))}</small></span></button>`;};
 $('itemList').innerHTML=rows.length?(topics?rows.map(menuButton).join(''):course.deliveries.map(menuButton).join('')+`<details class="case-menu" ${String(selected).startsWith('case-study')?'open':''}><summary>Four course case studies</summary>${course.caseStudies.map((r,i)=>menuButton(r,i+4)).join('')}</details>`):'<div class="empty">No topics match.<br><button id="clearFilters" type="button">Clear filters</button></div>';
 $('clearFilters')?.addEventListener('click',()=>{$('topicSearch').value='';$('blockFilter').value='';render();});
 $('itemList').querySelectorAll('[data-item]').forEach(button=>button.onclick=()=>{selected=topics?Number(button.dataset.item):button.dataset.item;location.hash=`${view}/${selected}`;});
 const active=$('itemList').querySelector('[aria-current="true"]');
 if(active){const row=active.getBoundingClientRect(),box=$('itemList').getBoundingClientRect();if(row.top<box.top||row.bottom>box.bottom)$('itemList').scrollTop+=row.top-box.top-box.height/2+row.height/2;}
 if(!rows.length){$('detail').innerHTML='<p class="empty">Try another word or clear the filters to explore the full syllabus.</p>';return;}
 const item=rows.find(r=>(topics?r.n:r.id)===selected);topics?renderTopic(item):renderDelivery(item);bindBrief(item);
}
function readHash(){const match=location.hash.match(/^#(topics|deliveries)\/([a-z0-9-]+)$/);if(match){const previous=view;view=match[1];selected=view==='topics'?Number(match[2]):match[2];if(previous!==view || (view==='topics'&&!filteredTopics().some(t=>t.n===selected))){$('topicSearch').value='';$('blockFilter').value='';}}render();}
function switchView(next){view=next;selected=next==='topics'?1:course.deliveries[0].id;$('topicSearch').value='';$('blockFilter').value='';location.hash=`${view}/${selected}`;if(location.hash===`#${view}/${selected}`)render();}
function openRules(notes=false){$('courseRules').showModal();if(notes)$('sourceNotes').scrollIntoView({block:'start'});else $('courseRules').scrollTop=0;}
function renderRules(){
 $('rulesContent').innerHTML=`<section class="rule-section"><h3>Five categories. The USAC weights.</h3>${course.assessment.map(a=>`<div class="weight-row"><span>${esc(a.name)}</span><strong>${a.weight}%</strong><p>${esc(a.course)}<br><strong>Evidence:</strong> ${esc(a.evidence)}<br>Use: ${esc(a.path)}</p></div>`).join('')}<p>These are published category weights, not your grades. The company’s definitions of done live in 00 - Manual/MANUAL.md; this Lab adds no points, penalties or scoring.</p></section><section class="rule-section"><h3>The seven official learning outcomes.</h3><ul>${list(course.outcomes)}</ul><h3>The 21 competence references.</h3>${(company?.competences||[]).map(c=>`<p class="competence-row"><span>${esc(c.id)}</span>${esc(c.text)}</p>`).join('')}<p>Read the <a href="COURSE-SYSTEM-PROMPT.md">included System Prompt</a> for the course definitions. Evidence and human mastery claims remain in the <a href="index.html#mastery">existing Mastery screen</a>.</p></section><section class="rule-section"><h3>Constraints and ownership.</h3>${course.rules.map(r=>`<h4><span class="badge">${esc(r.authority)}</span> ${esc(r.title)}</h4><p>${esc(r.text)}</p>`).join('')}</section><section class="rule-section"><h3>Published A–F scale.</h3><div class="scale">${course.gradeScale.map(r=>`<div><strong>${esc(r[0])}</strong><span>${esc(r[1])}</span></div>`).join('')}</div><p>A reference to the official scale. No student grades are entered or calculated here.</p></section><section class="rule-section" id="sourceNotes"><h3>Source differences to clarify.</h3>${course.discrepancies.map(d=>`<h4>${esc(d.title)}</h4><p>${esc(d.detail)}</p>`).join('')}</section><section class="rule-section"><h3>Sources included or held in course materials.</h3>${Object.values(course.sources).map(s=>`<div class="source-box"><strong>${esc(s.title)}</strong><br>${esc(s.locator)}<br>${s.href?`<a href="${esc(s.href)}">Read the included student document ↗</a>`:s.path?`Included source file: <code>${esc(s.path)}</code>`:esc(s.availability)}</div>`).join('')}<p>Only student-facing guidance and the student System Prompt are included. Original institutional documents and instructor notes are not bundled. The reviewed course mapping is <a href="learning-lab-data.json" download>available as structured data ↓</a>.</p></section>`;
}
try{
 const response=await fetch('learning-lab-data.json');if(!response.ok)throw Error('Course data unavailable');course=await response.json();
 for(const block of course.blocks){const option=document.createElement('option');option.value=String(block.id);option.textContent=`${block.span} · ${block.title}`;$('blockFilter').append(option);}
 $('topicSearch').addEventListener('input',render);$('blockFilter').addEventListener('change',render);
 $('deliveriesTab').onclick=()=>switchView('deliveries');$('topicsTab').onclick=()=>switchView('topics');
 document.querySelector('.lab-switch').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const target=e.key==='Home'?'deliveries':e.key==='End'?'topics':view==='topics'?'deliveries':'topics';switchView(target);$(target+'Tab').focus();});
 $('rulesOpen').disabled=false;$('rulesOpen').onclick=()=>openRules();$('rulesClose').onclick=()=>$('courseRules').close();
 addEventListener('hashchange',readHash);renderRules();readHash();
}catch(e){$('detail').innerHTML='<h2>The guide could not load.</h2><p class="error">Open Learning Lab through the local server and reload. Keep learning-lab-data.json beside this page. <a href="CORNERS-CITY-LOCALHOST.md">Read the startup guide ↗</a></p>';}
